import assert from "node:assert/strict";
import { envFlagTrue, isRebrand, isDemoLock, readBlabsFlags } from "./flags.js";
import { BLABS_DISPLAY_BRAND, UPSTREAM_DISPLAY_BRAND, getDisplayBrand } from "./brandConfig.js";
import { brandifyText } from "./brandifyText.js";
assert.equal(envFlagTrue("1"), true);
assert.equal(envFlagTrue("TRUE"), true);
assert.equal(envFlagTrue(" Yes "), true);
assert.equal(envFlagTrue("0"), false);
process.env.BLABS_REBRAND = "";
process.env.BLABS_DEMO_LOCK = "";
assert.deepEqual(readBlabsFlags(), { rebrand: false, demoLock: false });
assert.equal(getDisplayBrand(readBlabsFlags()), UPSTREAM_DISPLAY_BRAND);
process.env.BLABS_REBRAND = "1";
assert.equal(isRebrand(), true);
assert.equal(getDisplayBrand(readBlabsFlags()), BLABS_DISPLAY_BRAND);
process.env.BLABS_REBRAND = "";
process.env.BLABS_DEMO_LOCK = "1";
assert.equal(isDemoLock(), true);
assert.equal(getDisplayBrand(readBlabsFlags()), UPSTREAM_DISPLAY_BRAND);
assert.equal(brandifyText("Support 9Router", BLABS_DISPLAY_BRAND), "Support BLabsAIGate");
console.log("blabsFlagsSelfCheck: OK");
